apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-postupdate"
  labels:
    app: postupdate
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postupdate
        image: {{ .Values.drupal.image | quote }}
        command: ["/bin/sh", "-c"]
        args:
        - cd web;
          drush updatedb -n; drush config-import -n; drush entity-updates -n;
        env:
        - name: PRODUCTION_RELEASE_NAME
          value: {{ .Values.production_release_name | default "production" }}
        - name: PHP_FPM_CLEAR_ENV
          value: "no"
        - name: DB_USER
          value: "{{ .Values.mariadb.db.user }}"
        - name: DB_NAME
          value: "{{ .Values.mariadb.db.name }}"
        - name: DB_HOST
          value: "{{ .Release.Name }}-mariadb"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-mariadb"
              key: mariadb-password
      {{- range $key, $val := .Values.drupal.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        volumeMounts:
          - name: drupal-files-volume
            mountPath: /var/www/html/web/sites/default/files
          - name: drupal-dbdump-volume
            mountPath: /var/backups/db
      imagePullSecrets:
      - name: gcr
      volumes:
      - name: drupal-files-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-public-files
      - name: drupal-dbdump-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-dbdump